### ISSUE TITLE
Vertexloader error

### ISSUE THREAD

**Issue by sudha-vijayakumar** [tigergraph/graph-ml-notebooks#14]
Error source: (https://github.com/tigergraph/graph-ml-notebooks/blob/main/applications/fraud_detection/fraud_detection.ipynb)

Error Message:

Installing and optimizing queries. It might take a minute if this is the first time you use this loader.
---------------------------------------------------------------------------
ConnectionError                           Traceback (most recent call last)
[<ipython-input-80-616255a3393a>](https://localhost:8080/#) in <module>
----> 1 train_loader = conn.gds.vertexLoader(
      2     attributes=["in_degree","out_degree","send_amount","send_min",
      3                 "recv_amount","recv_min","pagerank", "is_fraud"],
      4     num_batches=1,filter_by="is_training"
      5 )

3 frames
[/usr/local/lib/python3.8/dist-packages/pyTigerGraph/gds/utilities.py](https://localhost:8080/#) in install_query_file(conn, file_path, replace, distributed, force)
    160     status = resp.splitlines()[-1]
    161     if "Failed" in status:
--> 162         raise ConnectionError(resp)
    163     else:
    164         print(status)

ConnectionError: Using graph 'Ethereum'

Type Check Error in query vertex_loader_1800ab04ea95dd6d88bdef6354f8ce05 (TYP-1002): line 64, col 42
Function/Tuple name does not exist: int_to_string
Failed to create queries: [vertex_loader_1800ab04ea95dd6d88bdef6354f8ce05].

**Comment by billshitg** [comment]
I guess you are not running the ml workbench on tgcloud? If so, the database needs to be activated. Please check here https://act.tigergraphlabs.com/ to get the activator. Also please let me know if there are any questions about it.

**Comment by zhixiany** [comment]
which tg db version you have, @sudha-vijayakumar ? for 3.8 in tgcloud you should have these activated already by default, otherwise need to manually activate it via https://act.tigergraphlabs.com/  as @billshitg mentioned?
